version: '3.8'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY_FILE: /run/secrets/directus_key
      SECRET_FILE: /run/secrets/directus_secret

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE_FILE: /run/secrets/postgres_db
      DB_USER_FILE: /run/secrets/postgres_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      # CACHE_REDIS: 'redis://cache:6379'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL_FILE: /run/secrets/admin_email
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password

    secrets:
      - directus_key
      - directus_secret
      - admin_email
      - admin_password
      - postgres_user
      - postgres_password
      - postgres_db

secrets:
  directus_key:
    file: ./directus_key.txt
  directus_secret:
    file: ./directus_secret.txt
  admin_email:
    file: ./admin_email.txt
  admin_password:
    file: ./admin_password.txt
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt
  postgres_db:
    file: ./postgres_db.txt




      # Admin config not working? Can be caused by a failed bootstrapping process if directus container crashed on first run
      # Directus config stored in local 'data' folder, must be deleted if you want to completely wipe the setup
      # Docker PS to get container ID of directus container
      # docker exec -t -i CONTAINER_ID /bin/sh
      # npx directus roles create --role Administrator --admin true 
      # Above command spits out a role ID
      # npx directus users create --email admin@example.com --password d1r3ctu5 --role <role-uuid-from-above>

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
