# This is a basic workflow to help you get started with Actions

name: SSH Connect

on: 
  workflow_dispatch:

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DO_SERVICES_IP }}
        username: ${{ secrets.DO_SERVICES_USERNAME }}
        password: ${{ secrets.DO_SERVICES_PASSWORD }}
        port: ${{ secrets.DO_SERVICES_SSH_PORT }}
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
