# This is a basic workflow to help you get started with Actions

name: Setup New Droplet

on: 
  workflow_dispatch:

jobs:
  run_init_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Droplet
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DO_SERVICES_IP }}
        username: ${{ secrets.DO_SERVICES_USERNAME }}
        password: ${{ secrets.DO_SERVICES_PASSWORD }}
        port: ${{ secrets.DO_SERVICES_SSH_PORT }}
        command_timeout: 30m
        script: | 
          sudo DEBIAN_FRONTEND=noninteractive apt update -y
          sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo DEBIAN_FRONTEND=noninteractive apt update -y
          apt-cache policy docker-ce
          sudo apt install docker-ce
